function cognemo_ringlabel(radius,fontsize)
%% Preamble
%{
This function places a ring of region-area labels around the connectogram
plots
%}
%%

areacolors = [[172 43 194];
              [214 143 226];
              [255 160 184];
              [255 225 184];
              [160 224 112];
              [12 135 93];
              [59 99 202];
              [197 0 4];
              [179 109 1];
              [119 65 25]]./255;


ring = [1    0.5     "\bf\color[rgb]{"+num2str(areacolors(1,:))+"}PFr";
        1    0.36    "\bf\color[rgb]{"+num2str(areacolors(2,:))+"}Fr";
        1    0.3193  "\bf\color[rgb]{"+num2str(areacolors(3,:))+"}Ins"; 
        1    0.1667  "\bf\color[rgb]{"+num2str(areacolors(4,:))+"}Tem";
        1.03 0       "\bf\color[rgb]{"+num2str(areacolors(5,:))+"}Par";
        1    1.8889  "\bf\color[rgb]{"+num2str(areacolors(6,:))+"}Occ";
        1    1.765   "\bf\color[rgb]{"+num2str(areacolors(7,:))+"}SbC";
        1    1.62    "\bf\color[rgb]{"+num2str(areacolors(8,:))+"}CeB";
        1    1.5     "\bf\color[rgb]{"+num2str(areacolors(9,:))+"}Ver";
        1.1  1.5     "\bf\color[rgb]{"+num2str(areacolors(10,:))+"}Bstem";
        1    1.38    "\bf\color[rgb]{"+num2str(areacolors(8,:))+"}CeB";
        1    1.235   "\bf\color[rgb]{"+num2str(areacolors(7,:))+"}SbC";
        1    1.1111  "\bf\color[rgb]{"+num2str(areacolors(6,:))+"}Occ";
        1.03 1       "\bf\color[rgb]{"+num2str(areacolors(5,:))+"}Par";
        1    0.8333  "\bf\color[rgb]{"+num2str(areacolors(4,:))+"}Tem";
        1    0.6807  "\bf\color[rgb]{"+num2str(areacolors(3,:))+"}Ins";
        1    0.64    "\bf\color[rgb]{"+num2str(areacolors(2,:))+"}Fr"];



%X = radius*str2double(ring(:,1)).*cospi(str2double(ring(:,2)));
X = radius*1*str2double(ring(:,1)).*cos(pi*str2double(ring(:,2)));
%Y = radius*str2double(ring(:,1)).*sinpi(str2double(ring(:,2)));
Y = radius*1*str2double(ring(:,1)).*sin(pi*str2double(ring(:,2)));
S = cellstr(ring(:,3));

TC = text(X(1),Y(1),S(1,:),...
         'Color','w',...
         'FontSize',fontsize,...
         'FontSmoothing','on',...
         'HorizontalAlignment','Center',...
         'VerticalAlignment','Bottom');
TR = text(X(2:4),Y(2:4),S(2:4,:),...
         'Color','w',...
         'FontSize',fontsize,...
         'FontSmoothing','on',...
         'HorizontalAlignment','Left',...
         'VerticalAlignment','Bottom');
MR = text(X(5),Y(5),S(5,:),...
         'Color','w',...
         'FontSize',fontsize,...
         'FontSmoothing','on',...
         'HorizontalAlignment','Left',...
         'VerticalAlignment','Middle');
BR = text(X(6:8),Y(6:8),S(6:8,:),...
         'Color','w',...
         'FontSize',fontsize,...
         'FontSmoothing','on',...
         'HorizontalAlignment','Left',...
         'VerticalAlignment','Top');  
BC = text(X([9,10]),Y([9,10]),S([9,10],:),...
         'Color','w',...
         'FontSize',fontsize,...
         'FontSmoothing','on',...
         'HorizontalAlignment','Center',...
         'VerticalAlignment','Top');
BL = text(X(11:13),Y(11:13),S(11:13,:),...
         'Color','w',...
         'FontSize',fontsize,...
         'FontSmoothing','on',...
         'HorizontalAlignment','Right',...
         'VerticalAlignment','Top');
ML = text(X(14),Y(14),S(14,:),...
         'Color','w',...
         'FontSize',fontsize,...
         'FontSmoothing','on',...
         'HorizontalAlignment','Right',...
         'VerticalAlignment','Middle');
TL = text(X(15:17),Y(15:17),S(15:17,:),...
         'Color','w',...
         'FontSize',fontsize,...
         'FontSmoothing','on',...
         'HorizontalAlignment','Right',...
         'VerticalAlignment','Bottom'); 
     
end