function cognemo_matrixlabel(arealabels,fontsize)
%% Preamble
%{
This function places a box of region-area labels around the matrix
plots
%}
N_r = length(arealabels);

areacolors = [[172 43 194];
              [214 143 226];
              [255 160 184];
              [255 225 184];
              [160 224 112];
              [12 135 93];
              [59 99 202];
              [197 0 4];
              [179 109 1];
              [119 65 25]]./255;
          

box  = [1    1   "\bf\color[rgb]{"+num2str(areacolors(1,:))+"}PFr";
        2    2   "\bf\color[rgb]{"+num2str(areacolors(2,:))+"}Fr";
        3    3   "\bf\color[rgb]{"+num2str(areacolors(3,:))+"}Ins"; 
        4    4   "\bf\color[rgb]{"+num2str(areacolors(4,:))+"}Tem";
        5    5   "\bf\color[rgb]{"+num2str(areacolors(5,:))+"}Par";
        6    6   "\bf\color[rgb]{"+num2str(areacolors(6,:))+"}Occ";
        7    7   "\bf\color[rgb]{"+num2str(areacolors(7,:))+"}SbC";
        8    8   "\bf\color[rgb]{"+num2str(areacolors(8,:))+"}CeB";
        9    9   "\bf\color[rgb]{"+num2str(areacolors(9,:))+"}Ver";
        10   10  "\bf\color[rgb]{"+num2str(areacolors(10,:))+"}Bstem"];
    
arealabelsunique = unique(arealabels,'stable'); l = 0;
for i = 1:length(arealabelsunique)
    m = sum(arealabels == arealabelsunique(i));
    box(i,1) = l + m/2;
    box(i,2) = l + m/2;
    l = l + m;
end

X = str2double(box(:,1)); Y = str2double(box(:,2)); S = cellstr(box(:,3));
Xfix = -2 * ones([1,size(box,1)]); Yfix =  (N_r+4) * ones([1,size(box,1)]);

Xlabelsmid = text(X(1:9),Yfix(1:9),S(1:9,:),...
                 'Color','w',...
                 'FontSize',fontsize,...
                 'FontSmoothing','on',...
                 'HorizontalAlignment','Right',...
                 'VerticalAlignment','Middle',...
                 'Rotation',90);
Xlabelsleft = text(X(10),Yfix(10),S(10,:),...
                 'Color','w',...
                 'FontSize',fontsize,...
                 'FontSmoothing','on',...
                 'HorizontalAlignment','Right',...
                 'VerticalAlignment','Top',...
                 'Rotation',90);
             
Ylabelsmid = text(Xfix(1:9),Y(1:9),S(1:9,:),...
                 'Color','w',...
                 'FontSize',fontsize,...
                 'FontSmoothing','on',...
                 'HorizontalAlignment','Right',...
                 'VerticalAlignment','Middle');
Ylabelsright = text(Xfix(10),Y(10),S(10,:),...
                 'Color','w',...
                 'FontSize',fontsize,...
                 'FontSmoothing','on',...
                 'HorizontalAlignment','Right',...
                 'VerticalAlignment','Top');
